init python:
    #!/usr/bin/env python3
    # -*- coding: utf-8 -*-

    questionary = {
        "Culture Generale": [
            ["Quelle est la date de mort de Michael Jackson", [True, "2009"], [False, "2008"], [False, "2010"], [False, "2005"]],
            ["Comment appelle-t-on un bateau à trois coques", [True, "Un trimaran"], [False, "Un catamaran"], [False, "Un monocoque"], [False, "Un quadrimaran"]],
            ["Combien y a-t-il de joueurs sur le terrains dans une équipe de Base-ball", [True, "9"], [False, "8"], [False, "10"], [False, "7"]],
            ["Quel peuple a inventé la poudre a canon", [True, "Les Chinois"], [False, "Les Japonais"], [False, "Les Français"], [False, "Les Russes"]],
            ["Sur quel continent se trouve la Terre-Adélie", [True, "Antarctique"], [False, "Amérique"], [False, "Asie"], [False, "Afrique"]],
            ["De quoi se nourrit le manchot", [True, "Plancton"], [False, "Morue"], [False, "Bar"], [False, "Poisson chat"]],
            ["Qui est la première personne a avoir mis le pied sur la lune", [True, "Neil Armstrong"], [False, "Buzz Aldrin"], [False, "Charles Conrad"], [False, "David Scott"]],
            ["En combien de temps la Terre tourne autour du Soleil", [True, "365 jours et un quart"], [False, "365 jours"], [False, "365 jours et 2 quart"], [False, "365 jours et 3 quart"]],
            ["Qui a offert le statue de la liberté aux Etats-Unis", [True, "La France"], [False, "Le Vatican"], [False, "Le Royaume-Uni"], [False, "La Chine"]],
            ["Ou vit le Petit Prince", [True, "Sur l'astéroide B-612"], [False, "Sur la lune"], [False, "Sur Mars"], [False, "Sur Terre"]],
            ["Serguei Rachmaninov est resté dans les mémoires comme", [True, "Compositeur"], [False, "Dictateur"], [False, "Pianiste"], [False, "Physicien nucléaire"]],
            ["Où est né Mozart", [True, "Salzbourg"], [False, "Paris"], [False, "Budapest"], [False, "Vienne"]],
            ["Quel est le titre de Kim-Jong Un", [True, "Dirigeant suprême"], [False, "Maréchal de la République"], [False, "Seccrétaire général du parti communiste"], [False, "Dictateur"]],
            ["Quel dictateur dirigea l’URSS du milieu des années 1920 à 1953", [True, "Staline"], [False, "Trotski"], [False, "Lénine"], [False, "Molotov"]],
            ["Qui était le dieu de la guerre dans la mythologie grecque", [True, "Arès"], [False, "Apollon"], [False, "Hermès"], [False, "Hadès"]],
            ["Dans quel pays peut-on trouver la Catalogne et la Castille", [True, "l'Espagne"], [False, "l'Italie"], [False, "La France"], [False, "Le Portugal"]],
            ["A quel écrivain attribue-t-on la rédaction de l’Illiade et l’Odyssée", [True, "Homère"], [False, "Virgile"], [False, "Euripide"], [False, "Sophocle"]],
            ["Quel est le plus long fleuve de France la partie coulant sur le territoire", [True, "La loire"], [False, "Le Rhone"], [False, "Le Rhin"], [False, "La Seine"]],
            ["Le drapeau russe est blanc bleu et...", [True, "Rouge"], [False, "Jaune"], [False, "Vert"], [False, "Noir"]],
            ["Quel journal a été attaqué par des terroristes islamistes en janvier 2015", [True, "Charlie Hebdo"], [False, "Libération"], [False, "Le monde"], [False, "Le Figaro"]],
            ["Quelle est la date de la signature de l’armistice de la première Guerre mondial", [True, "Le 11 Novembre 1918"], [False, "Le 11 Novembre 1919"], [False, "Le 8 Mai 1918"], [False, "Le 8 Mai 1919"]],
            ["Combien de jours une année bissextile compte-t-elle", [True, "366"], [False, "365"], [False, "367"], [False, "364"]],
            ["Parmi les pays suivant lequel n’est pas membre de l’Union européenne", [True, "La Norvège"], [False, "La Suède"], [False, "Le Danemark"], [False, "La Finlande"]],
            ["Parmi les films suivants lequel n’a pas été réalisé par Steven Spielberg", [True, "Gladiator"], [False, "Il faut sauver le soldat Ryan"], [False, "E.T."], [False, "Les Dents de la mer"]],
            ["Que signifie l’adjectif volubile", [True, "Qui parle beaucoup"], [False, "Qui parle peu"], [False, "Qui est agressif"], [False, "Qui est gros et gras"]],
            ["De quand date le plus ancien témoignage d’écriture connu", [None, "33 av. JC"], [None, "330 av. JC"], [None, "33 000 av. JC"], [True, "3300 av. JC"]],
            ["Qui a composé « l’Ode a la joie », hymne de l’Union européenne", [True, "Beethoven"], [False, "Wagner"], [False, "Haydn"], [False, "Mozart"]],
            ["Combien de films sur la saga Harry Potter ont été réalisés", [True, "8"], [False, "7"], [False, "6"], [False, "9"]],
            ["Quel animal peut être marteau, tigre ou pèlerin", [True, "Le requin"], [False, "La baleine"], [False, "L'orque"], [False, "Le moustique"]],
            ["En quelle année Neil Armstrong a-t-il déclaré : \"C’est un petit pas pour l’homme mais, un bon de géant pour l’humanité\"", [True, "1969"], [False, "1966"], [False, "1968"], [False, "1967"]]
        ],
        "Mangas": [
            ["Dans l’animé One Piece comment Luffy obtient t’il ses pouvoirs", [True, "Il les obtient en mangeant un fruit"], [False, "Il les obtient en méditant"], [False, "Il les obtient en se battant"], [False, "Il les possède depuis sa naissance"]],
            ["Dans Bleach comment s’appelle les sabres des shinigami", [True, "Zanpakuto"], [False, "Bankai"], [False, "Katana"], [False, "Nodachi"]],
            ["Quel est le manga ayant fait le plus de vente", [True, "One Piece"], [False, "Dragon Ball"], [False, "L'attaque des titans"], [False, "Naruto"]],
            ["Quel est l’élément du personnage principale de Fairy Tail", [True, "Le feu"], [False, "L'électricité"], [False, "Le vent"], [False, "L'acier"]],
            ["Quel Kaio Shin a aspiré boo avant de devenir gros dans Dragon Ball", [True, "Sud"], [False, "Nord"], [False, "Est"], [False, "Ouest"]],
            ["Quel est le nom du personnage principal de My hero Academia", [True, "Midoriya Izuku"], [False, "Shoto Todoroki"], [False, "Katsuki Bakugo"], [False, "Deku"]],
            ["Dans Damachi par quoi le personnage principal se fait t’il poursuivre dans le Donjon la première fois", [True, "Un minautore"], [False, "Un Troll"], [False, "Un Dragon"], [False, "Une Manticore"]],
            ["Quel est le sport pratiquer dans Haikyuu", [True, "Le Voley-ball"], [False, "Le Basket-ball"], [False, "Le Football"], [False, "La natation"]],
            ["Dans Death Note comment s’appelle l’inspecteur le plus intelligent de l’œuvre", [True, "L"], [False, "N"], [False, "M"], [False, "A"]],
            ["Quel membres a perdu le personnage principale de Fullmetal alchimist", [True, "Son bras droit et sa jambe gauche"], [False, "Ses deux bras"], [False, "Ses deux jambes"], [False, "Son bras gauche et sa jambe droite"]],
            ["Quel est le type d’aura de Hisoka dans Hunter x Hunter", [True, "transformation"], [False, "matérialisation"], [False, "renforcement"], [False, "spécialisation"]],
            ["Dans Code Geass quel est la nourriture préférer de C.C.", [True, "La pizza"], [False, "Les burgers"], [False, "Kebab"], [False, "Tacos"]],
            ["Dans Naruto qui est le septième Hokage", [True, "Naruto Uzumaki"], [False, "Kakashi Hatake"], [False, "Tsunade"], [False, "Minato Namikaze"]],
            ["Dans One punsh man en combien d’année d’entraînement Saitama deviens t’il invincible", [True, "3"], [False, "10"], [False, "1"], [False, "2"]],
            ["Dans Parasyte quelle partie du corps du personnage principal est modifiée par un parasite", [True, "La main droite"], [False, "Jambre gauche"], [False, "Les Yeux"], [False, "Le cerveaux"]],
            ["Dans Your lie in april de quel instrument joue le personnage principal", [True, "Du piano"], [False, "Du violon"], [False, "De la guitare"], [False, "Du Ukulélé"]],
            ["Dans Sword art online quel est le nom de la fille qui voulait se suicider avec Kirito quand tout les membre de leurs guilde étaient mort", [True, "Sachi"], [False, "Asuna"], [False, "Yui"], [False, "Silica"]],
            ["Dans Assassination Classroom a quel vitesse va le professeur", [True, "Mag 20"], [False, "Mag 10"], [False, "Mag 5"], [False, "Mag 1"]],
            ["Dans Tensei Shitara no Slime datta ken comment s’appelle le dragon au début de l’histoire", [True, "Veldora"], [False, "Rimuru"], [False, "Gobuta"], [False, "Benimaru"]],
            ["Dans Soul eater avec quoi le personnage principal se bat-il", [True, "Une faux"], [False, "Un katana"], [False, "Un nodachi"], [False, "Des dagues"]],
            ["Dans Hamatora à quelle distance Nice peut-il utiliser son pouvoir", [True, "5 mètres"], [False, "10 mètres"], [False, "50 mètres"], [False, "1 mètre"]],
            ["Dans l'animé no game no life combien de défaites ont subit les héros", [True, "0"], [False, "1"], [False, "2"], [False, "3"]],
            ["Dans le film no game no life 0 quel Dieu met fin à la guerre", [True, "Le Dieux des jeux"], [False, "Le Dieu de la guerre"], [False, "Le Dieu de la mort"], [False, "Les Dieux des différ races"]],
            ["Dans Baki quel est le surnom du père de Baki", [True, "L'ogre"], [True, "La créature al plus forte de la Terre"], [False, "L'hyumain le plus fort"], [False, "Unchained"]],
            ["Combien d'évolution les pokémons peuvent-ils avoir dans Pokémon", [True, "0"], [False, "1"], [False, "2"], [False, "3"]],
            ["Qui est le père du perosnnage principal de Blue Exorcist", [True, "Satan"], [False, "Un exorciste"], [False, "Un religieux"], [False, "Dieu"]],
            ["Quel est la particularité du gouffre où les personnages se dirigent dans Made in Abyss", [True, "Les personnages reçoivent une malédiction"], [False, "Des monstres attaquent les personnages"], [False, "Les personnages ne peuvent pas en resortir"], [False, "Il est extrêmement profond"]],
            ["A quel âge Gon et son père ont passé l'examin Hunter dans Hunter x Hunter", [True, "12"], [False, "16"], [False, "14"], [False, "18"]],
            ["Qui a infligé les cicatrices de Luffy dans One Piece", [True, "Luffy"], [False, "Zoro"], [False, "Crocodyle"], [False, "Marshal D Teach"]],
            ["Combien de parties de Jojo's bizarre Adventure ont été adaptées en animé", [True, "5"], [False, "4"], [False, "6"], [False, "8"]],
            ["Quel était le personnage oublié par les personnages de Re:Zero sauf par Subaru Natsuki", [True, "Rem"], [False, "Ram"], [False, "La Reine"], [False, "Emilia"]],
            ["Dans Charlotte qu'a fait Yu Otosaka pour enlever les super pouvoirs du monde", [True, "Il vole tous les pouvoirs grâce au sien"], [False, "Il tue tous les détenteurs de pouvoir"], [False, "Il les enferme tous dans une prison interdimensionnelle"], [False, "Il les a fait vieillir"]],
            ["Dans l'attaque des titans quel est le titan qui se bat pour protéger les humains dans la saison 1", [True, "Eren"], [False, "Mikasa"], [False, "Armin"], [False, "Erwin"]],
            ["Comment les personnages de Toriko deviennent-ils fort", [True, "Ils mangent"], [False, "Ils méditent"], [False, "Ils se battent"], [False, "Ils tuent des monstres"]],
            ["Que sont les animes \"Isekai\"", [True, "Des animes qui se passent dans un autre monde"], [False, "Des animes de combat"], [False, "Des animes de tranche de vie"], [False, "Des animes de musique"]],
            ["Dans UQ Holder quelle est la race du personnage principal", [True, "Vampire"], [False, "Kitsune"], [False, "Humain"], [False, "Loup Garou"]],
            ["Dans \"Sakamoto desu ga ?\" Pourquoi le personnage principal est-il connu", [True, "Il est montré comme parfait"], [False, "Il est montré comme très intelligent"], [False, "Il est montré comme très sportif"], [False, "Il est montré comme très drôle"]],
            ["Combien y a-t-il de prodige dans High School Prodigies Have it Easy Even In another World", [True, "7"], [False, "5"], [False, "9"], [False, "3"]],
            ["Quel est le pouvoir principal de Demon Slayer", [True, "La respiration"], [False, "Des techniques de sabre"], [False, "Des transformations"], [False, "Les arts martiaux"]],
            ["Dans Demon Slayer de quel chanteur est inspiré le méchant", [True, "Michael Jackson"], [False, "Whitney Houston"], [False, "Jimi Hendrix"], [False, "Jim Morrison"]]
        ],
        "Musique": [
            ["De combien de corde est composée un violon", [False, "6"], [True, "4"], [False, "8"], [False, "5"]],
            ["Via quoi le son ne se transmet pas", [False, "les solides"], [False, "la matière non-newtonnienes"], [True, "le vide"], [False, "le plasma"]],
            ["avec quoi frotte-on les cordes d’un instrument à cordes frottées", [False, "arc"], [True, "archet"], [False, "vielle"], [False, "fibre"]],
            ["Comment se nomme la transcription écrite des caractéristiques du son musical", [True, "partition"], [False, "octave"], [False, "caractère manuscrit"], [False, "les notes"]],
            ["Où est né bethoven", [False, "Allemagne"], [False, "Autriche"], [False, "Saint empire romain"], [False, "Suisse"]],
            ["quel tambour peut avoir un diamètre de 12 à 70cm", [False, "tambourin"], [True, "tar"], [False, "daf"], [False, "bendir"]],
            ["De qui est la chanson Echoes", [False, "Pink Floyd"], [False, "Freddy Mercurry"], [True, "Roger Waters"], [False, "Slim Harpo"]],
            ["Combien de corde peut possédé la lyre", [False, "7"], [False, "4"], [False, "9"], [True, "12"]],
            ["Combien de touches possèdent les piano", [False, "36"], [False, "52"], [True, "88"], [False, "100"]],
            ["De quel mot italien vient ocarina", [True, "oie"], [False, "oiseau"], [False, "orange"], [False, "Nom de famille italien"]],
            ["Combien d’album porte le nom Falmingo", [False, "1"], [False, "2"], [True, "3"], [False, "5"]],
            ["Comment se nomme une œuvre musicale et théâtrale pour un orchestre et des chanteurs", [True, "opéra"], [False, "cinema"], [False, "balai"], [False, "bal"]],
            ["Comment se nomme l’hymne américaine", [False, "God save the Queen"], [True, "The star-Spangled Banner"], [False, "The final mission"], [False, "Our hope"]],
            ["A quel age est mort Freddy Mercury", [True, "45"], [False, "55"], [False, "50"], [False, "60"]],
            ["Qui est à la batterie dans le groupe U2", [True, "Larry Mullen Jr."], [False, "Bono"], [False, "Adam Clayton"], [False, "The edge"]],
            ["Quel genre est dérivé du Rock", [True, "Pop"], [False, "Jazz"], [False, "Blues"], [False, "Slam"]],
            ["Comment est appelé un jeu vidéo où le style de jeu est basé autour de musique", [False, "jeu de course"], [True, "jeu de rythme"], [False, "beat them up"], [False, "osu like"]],
            ["Dans quel siecle est arrivé l’accordéon en Europe", [True, "17"], [False, "18"], [False, "19"], [False, "5"]],
            ["Quelle est la caractéristique de la flûte harmonique", [False, "elle ne peut pas faire de fausse note"], [True, "elle n’a pas de trous pour les doigt"], [False, "elle est très dure à prendre en main"], [False, "elle se joue à l’aide d’une corde en son extremité"]],
            ["Lequel de ces instrument n’a pas de membrane", [False, "caisse claire"], [False, "dabakan"], [False, "Daf"], [True, "Chocalho"]],
            ["Quel métal désigne une catégories d’instrument à vent", [True, "Cuivre"], [False, "Acier"], [False, "Or"], [False, "Bronze"]],
            ["Quel catégorie d’instrument à corde le piano appartient-il", [True, "corde frappé"], [False, "corde frotté"], [False, "c’est un instrument à vent"], [False, "c’est un instrument à percutions"]],
            ["Combien de cordes possèdent le luth", [False, "6"], [False, "8"], [True, "10"], [False, "4"]],
            ["Dans quelle ville est né Charles Gainsbourg", [True, "Paris"], [False, "Bruxelles"], [False, "Marseilles"],[False, " Bordeaux" ]],
            ["Quels groupe est à l’origine de Your time is gonna come", [True, "Led zeppelin"], [False, "Aerosmith"], [False, "Rolling stone"],[False, "Beattle" ]],
            ["Avec quel groupe Ronnie James Dio a collaboré", [True, "Black Sabbath"], [False, " Led Zeppelin"], [False, "Gorillaz"],[False, "Beattle" ]],
            ["Quels manga possède des personnagess ayant un nom venant du monde de la musique", [True, "JoJo’s bizarre adventure"], [False, "Your lie in april"], [False, "Goldorack (version japonaise)"],[False, "pokemon" ]],
            ["Qui est l’auteur de la chanson Soft and wet", [True, "Prince"], [False, " Ronnie James Dio"], [False, "David Bowie"],[False, "Queen" ]],
            ["Combien d’album le coffret Crazy Diamond contient-il", [True, "3"], [False, "2"], [False, "5"], [False, "7" ]],
            ["Quel est l’origine du compositeur Michelle Polnareff", [True, "Français"], [False, " Amériquain"], [False, "Anglais"],[False, "Allemand" ]],
            ["Qui est l’auteur de la chanson King Nothing", [True, "Métalica"], [False, " Aerosmith"], [False, " Polnareff"],[False, "Black sabbath" ]],
            ["Qui est l’auteur de la chanson Paisley Park", [True, "Prince"], [False, " Queen"], [False, " Polnareff"],[False, " Dio" ]],
            ["Qui est l’auteur de l’album Doggy Style", [True, "Snoup dog"], [False, " Ice T"], [False, " Tupac"],[False, " Eminem" ]],
            ["Qui est le chanteur du groupe Queen", [True, "Freddy Mercury"], [False, " Fred Ymercury"], [False, "Freddymer Curry"],[False, "Dio" ]],
            ["Quels sont les surnoms de Michael Jackson", [True, "Le roi de la pop et Bambi"], [False, " Le roi de la pop et Dandy"], [False, "Le Roi du Rock et Dandy"],[False, "Le Roi du Rock et Bambi" ]],
            ["Qui est l’auteur de la chanson Les Feuilles Mortes", [True, "Prévert"], [False, "Polnareff"], [False, "Gainsbourg"],[False, "Stromae" ]],
            ["Quand est sorti l’album Sticky Fingers des Rollings Stones", [True, "1971"], [False, "1980"], [False, " 1975"],[False, "1974" ]],
            ["Qui est l’auteur de la chanson Purple Haze", [True, "Jimmi Hendrix"], [False, " Dio"], [False, " Freddy Mercury"],[False, "Polnareff" ]],
            ["Quel est la nationalité de Iggy Pop", [True, "Américain"], [False, " Anglais"], [False, "  Français"],[False, " Allemand" ]],
            ["De quoi est constitué la pochette de l’album de Diver Down", [True, " Deux triangles rouges sur fond blanc"], [False, " Deux cercles bleu sur fond vert "], [False, " Deux bananes roses avec des bandanas"],[False, " Trois pommes rouges sur fond de cerises verts" ]],
            ["Quelle note joue le diapason", [True, "La"], [False, " Do"], [False, " Sol"],[False, " Re" ]],
        ],
        "Programmation": [
            ["Qu'est-ce qu'une variable", [True, "Un espace de stockage mémoire servant à contenir une donnée"], [False, "Une variation brusque de le tension électrique affectant le fonctionnement de la machine"], [False, "La moyenne de l'utilisation du processeur par unité de temps"]],
            ["Qu'est-ce qu'une procédure", [False, "Une méthode de travail"], [False, "Une action judicaire"], [True, "Un sous-programme permettant d'effectuer une opération spécifique"]],
            ["Qu'est-ce qu'une fuite mémoire", [False, "Un trou creusé dans une barette de RAM"], [False, "Une allocation de mémoire non libérée dans un programme"], [True, "Une perte de donnée due à un plantage de la machine"]],
            ["Qu'est-ce que l'héritage", [False, "Ce que je vais recevoir au décès de ma tante"], [False, "Un des fondements de la POO qui permet la réutilisation et la spécialisation de types de données"], [True, "La possibilité d'appliquer un patch correctif à un programme"]],
            ["Lors de la compilation et de l'édition des liens, un commentaire:", [False, "Augmente la taille d'un programme exécutable"], [False, "Diminue la taille d'un programme exécutable"], [True, "Ne change pas la taille d'un programme exécutable"]],
            ["En programmation:", [False, "0 est positif"], [False, "0 est négatif"], [True, "Les deux réponses sont correctes"]],
            ["Quest-ce qu'un pointeur", [True, "Une adresse mémoire où se situe le contenu d'une variable"], [False, "Un périphérique d'entrée programmable (souris, crayon optique, ...)"], [False, "Un pédophile emprisonné"]],
            ["Lequel de ces langages n'est pas 'orienté objet'", [False, "C++"], [False, "Java"], [True, "Assembleur"]],
            ["Qu'est-ce qu'une fonction", [False, "Une fonctionnalité proposée par un programme"], [True, "Une procédure renvoyant un résultat"], [False, "Le résultat d'une fonction mathématique"]],
            ["Qu'est-ce que la récursivité", [True, "Une technique qui permet à une fonction ou une procédure de s'appeler elle-même"], [False, "Un bug qui provoque l'appel en boucle d'une fonction ou d'une procédure"], [False, "Une technique qui permet d'afficher toutes les polices d'un programme en 'cursive'"]],
            ["Qu'est-ce qu'un fichier .exe", [True, "Un fichier permettant de lancer un programme sur Windows"], [False, "Un fichier permettant de lancer un programme sur Linux"], [False, "Un fichier permettant de lancer un programme sur Mac"]],
            ["Comment s'appellent les langages comme le python", [True, "Des langages interprêtés"], [False, "Des langages compilés"], [False, "Des langages pythonesques"]],
            ["Comment s'appellent les langages comme le C++", [True, "Des langages compilés"], [False, "Des langages interprêtés"], [False, "Des langages céistes"]],
            ["Qu'est-ce qu'un tuple", [True, "une liste immuable"], [False, "un dictionnaire immuable"], [False, "un type de variable"]],
            ["Comment appelle-t-on une variable ayant comme valeur soit True ou False", [True, "Des variables booléennes"], [False, "Des variables entières"], [False, "Des variables binaires"]],
            ["Qu'est-ce que le langage HTML", [True, "Un langage de balisage"], [False, "HyperText Markup Language"], [False, "Un langage de programmation"]],
            ["Qu'est-ce que le protocole HTTP", [True, "Un protocole permettant aux clients d'accéder au serveur"], [False, "Un protocole permettant de réduire l'inflation de la pandémie de COVID-19"], [False, "Un protocole secret utilisé par la CIA dans la zone 51"]],
            ["Que signifie HTTP", [True, "HyperText Transfer Protocol"], [False, "Hot Text Transfer Protocol"], [False, "HyperText Trick Party"]],
            ["Que signifie HTTPS", [True, "Que c'est une connexion sécurisée"], [False, "Que c'est une connexion anonyme"], [False, "Que c'est une \"Soft\" connexion"]],
            ["En quelles circonstances est utilisé le PHP", [True, "Quand on travaille avec une base de données"], [False, "Quand on veut faire une page Web"], [False, "Quand on veut styliser sa page Web"]],
            ["Que signifie CSS", [True, "Cascading Style Sheet"], [False, "Closing Space Show"], [False, "Cascading Style Shit"]],
            ["Qu'est-ce que le CSS", [True, "Un langage de style"], [False, "Un langage stylé"], [False, "Un langage de balisage"]],
            ["Quel est le langage de programmation utilisé, le plus souvent, pour le Web", [True, "Javascript"], [False, "C++"], [False, "Go"]],
            ["Qu'est-ce qu'un invité de commandes", [True, "Un logiciel permettant d'intéragir avec le système"], [False, "Un logiciel permettant de réagir au système"], [False, "Un invité dans une soirée qui prend nos commandes"]],
            ["Qu'est-ce que Windows", [True, "Un système d'exploitation"], [False, "L'ancien nom de Microsoft"], [False, "Le petit frère de Linux"]],
            ["Qu'est-ce qu'un moteur de recherche", [True, "Un site web nous permettant de trouver d'autres pages web en entrant des mots-clés"], [False, "Un logiciel lisant le code d'une page web et nous affiche le rendu"], [False, "Une sorte de moteur que l'on met dans sa voiture et nous emmène au lycée tout seul"]],
            ["Quand est sortie la toute première version d'un système UNIX", [True, "En 1970"], [False, "1981"], [False, "2001"]],
            ["Qu'est-ce qu'un navigateur internet", [True, "C'est un logiciel qui traduit le code reçu d'une page web et crée un rendu sur l'écran du code avec les balises enlevées, le style rajouté, etc..."], [False, "Un site web nous permettant de trouver d'autres pages web en entrant des mots-clés"], [False, "C'est un robot qui vous donne l'adresse d'une page web après votre recherche"]],
            ["Que veut dire coder", [True, "Ecrire du code, dans n'importe quel langage"], [False, "C'est voler mais on a mal entendu"], [False, "C'est comme encoder mais on le fait manuellement"]],
            ["Que veut dire programmer", [True, "Ecrire du code dans un langage de programmation qui seront interprétées par l'ordinateur"], [False, "Inventer des fonctionnalités et des fonctions"], [False, "Faire une page HTML"]],
            ["Que veut dire développer", [True, "C'est concevoir des logiciels, en écrivant un code source, qui sera ensuite interprété et exécuté par l’ordinateur"], [False, "C'est l'action d'enlever l'enveloppe de quelque chose"], [False, "J'en ai aucune idée"]],
            ["A quoi sert la fonction \"input\" en Python", [True, "A récupérer une information de l'utilisateur"], [False, "A faire entrer une information dans un programme"], [False, "A faire le contraire de la fonction \"exit\""]],
            ["A quoi sert le mot clé et la fonction \"return\" en Python", [True, "A renvoyer une valeur"], [False, "A renvoyer un employé tout en restant à son bureau"], [False, "A inverser l'ordre d'action d'un fonction"]],
            ["Que fait une boucle \"for\" en Python", [True, "Elle prend chaque élément d'une liste/dictionnaire/tupe/chaine de caractères et suis un suite d'opérations définies à l'intérieur de celle-ci"], [False, "Elle récupère un élément précis dans une liste et exécute les opérations à l'intérieur de celle-ci"], [False, "Elle prend chaque élément d'une liste et suis un suite d'opérations définies à l'intérieur de celle-ci"]],
            ["Que fait une boucle \"while\" en Python", [True, "Elle effectue une action tant que la condition de départ est correcte"], [False, "Elle effectue une action pendant qu'une fonction s'exécute"], [False, "Elle n'existe pas en Python"]],
            ["Que sera le type de la variable x ayant comme valeur 2.5 en Python", [True, "float"], [False, "int"], [False, "bool"]],
            ["Quelle est la différence entre \"is\" et \"==\" en Python", [True, "is permet de vérifier si la redirection de l'objet final de la valeur de la variable est bien la même que le second argument"], [False, "Il n'y en a pas, ils font la même action"], [False, "== permet de vérifier si la redirection de l'objet final de la valeur de la variable est bien la même que le second argument"]],
            ["Pourquoi utilise-t-on une fonction", [True, "Parce qu'on va appeler plusieurs fois les mêmes instructions"], [False, "Juste pour faire beau"], [False, "Parce que c'est mathématique"]],
            ["Comment appelle-t-on une fonction présente dans une classe", [True, "Une méthode"], [False, "Une fonction"], [False, "Une classe ne supporte pas les fonctions en son sein"]],
            ["Comment appelle-t-on une variable présente dans une classe", [True, "Une propriété"], [False, "Une variable"], [False, "Une classe ne supporte pas les variables en son sein"]],
        ]
    }
